### ISSUE TITLE
Error received when trying to upload from Device to Shared Cloud

### ISSUE THREAD

**Issue by mlockrey** [lborgman/easy-cap-ed#113]
In URL: 
* https://easycaped-1.firebaseapp.com/caped-editor.html?addedNew=YouTube&loadFrom=local&key=YT-EiGZBs1N6LQ

Error: elt id not found
    at uploadElt (https://easycaped-1.firebaseapp.com/js/sync.js:320:29)
    at uploadEltFromCopy (https://easycaped-1.firebaseapp.com/js/sync.js:728:38)
    at walkTheElementDOM (https://easycaped-1.firebaseapp.com/js/sync.js:836:5)
    at walkTheElementDOM (https://easycaped-1.firebaseapp.com/js/sync.js:839:9)
    at walkTheElementDOM (https://easycaped-1.firebaseapp.com/js/sync.js:839:9)
    at https://easycaped-1.firebaseapp.com/js/sync.js:758:13

Error source:
* unhandledrejection

Context:
* Version: 0.64.44
* Started: 2018-01-18T00:34
* Now:     2018-01-18T00:38
* Elapsed: 243.404 sec
* Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3314.0 Safari/537.36
* Symbol(local)
* Logged in

**Comment by mlockrey** [comment]
Seems to work when I close down the error modal although there's no confirmation once the uploading animation reaches it's end point, but if I navigate back to the "Device" button option in the top right hand corner, I can see that the captions are now available for editing on my shared cloud (see attached screenshot).

![screen shot 2018-01-18 at 11 41 24 am](https://user-images.githubusercontent.com/17226874/35074949-95fa13dc-fc44-11e7-8ded-e0dc5197026b.png)

**Comment by lborgman** [comment]
@mlockrey Thanks, strange. I have no idea what happens there. Did you do anything during the upload or did you just wait for it to finish?

**Comment by lborgman** [comment]
Tried to reproduce it, but I did not see the problem. Added a bit better error reporting in 0.64.52

@mlockrey Please report the error if you see it again.
