### ISSUE TITLE
TypeError: Cannot read property 'replaceChild' of null

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#125]
In URL: 
* https://easycaped-1.firebaseapp.com/caped-editor.html?addedNew=YouTube&loadFrom=local&key=YT-7NVYKC8ud7Q

TypeError: Cannot read property 'replaceChild' of null
    at addPunctChar (https://easycaped-1.firebaseapp.com/js/transcribe.js:869:35)
    at Object.my.punctuation (https://easycaped-1.firebaseapp.com/js/transcribe.js:892:31)
    at mstfPunctPeriod (https://easycaped-1.firebaseapp.com/js/our-mousetraps.js:556:16)
    at _fireCallback (https://easycaped-1.firebaseapp.com/js/external/my-mousetrap.js:646:17)
    at Mousetrap.self._handleKey (https://easycaped-1.firebaseapp.com/js/external/my-mousetrap.js:707:21)
    at Mousetrap.handleKey (https://easycaped-1.firebaseapp.com/js/external/my-mousetrap.js:1041:32)
    at Mousetrap._handleKey (https://easycaped-1.firebaseapp.com/js/external/my-mousetrap-record.js:88:28)
    at Mousetrap.handleKey (https://easycaped-1.firebaseapp.com/js/external/my-mousetrap-record.js:250:20)
    at HTMLDocument._handleKeyEvent (https://easycaped-1.firebaseapp.com/js/external/my-mousetrap.js:767:18)

Error source:
* error

Context:
* Version: 0.64.55
* Started: 2018-01-29T18:34
* Now:     2018-01-29T18:35
* Elapsed: 53.625 sec
* Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36
* Symbol(local)
* Transcript
* Logged in

**Comment by lborgman** [comment]
@MikeRidgway Thanks, should be fixed in 0.64.57
