### ISSUE TITLE
Not sure what caused this

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#141]
### Error Popup Message in EasyCapEd (automatically copied)
In URL: 
* https://easycaped-1.firebaseapp.com/caped-editor.html?addedNew=YouTube&loadFrom=local&key=YT-Mkd3LNg78RA

Error: select which range? from=A
    at setRangeInContenteditable (https://easycaped-1.firebaseapp.com/js/caped-editor.js:2703:15)
    at setTimeout (https://easycaped-1.firebaseapp.com/js/caped-editor.js:2665:24)

Error source:
* error

Context:
* Version: 0.65.85
* Started: 2018-04-09T00:38
* Now:     2018-04-09T00:46
* Elapsed: 520.904 sec
* Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
* Symbol(local)
* Captions
* Logged in

**Comment by lborgman** [comment]
Can't reproduce it now.
