### ISSUE TITLE
Tried to hit enter key to edit word

### ISSUE THREAD

**Issue by dtmpsc** [lborgman/easy-cap-ed#146]
### Expected Behavior (if any)
Wanted to revise text with edit mode.

### Actual Behavior (if any)
hitting enter key gives error, had to use mouse to click on word to get to edit mode.

### Steps to Reproduce (if any)
hit enter key while word is highlighted

### Error Popup Message in EasyCapEd (automatically copied)
In URL: 
* https://easycaped-1.firebaseapp.com/caped-editor.html?loadFrom=local&key=YT-oFlGrWkNK5c

ReferenceError: focusWordFromKeyboard is not defined
    at mstfEasyNedCCEditByEnter (https://easycaped-1.firebaseapp.com/js/our-mousetraps.js:1469:9)
    at _fireCallback (https://easycaped-1.firebaseapp.com/js/external/my-mousetrap.js:653:17)
    at Mousetrap.self._handleKey (https://easycaped-1.firebaseapp.com/js/external/my-mousetrap.js:714:21)
    at Mousetrap.handleKey (https://easycaped-1.firebaseapp.com/js/external/my-mousetrap.js:1057:32)
    at Mousetrap._handleKey (https://easycaped-1.firebaseapp.com/js/external/my-mousetrap-record.js:96:28)
    at Mousetrap.handleKey (https://easycaped-1.firebaseapp.com/js/external/my-mousetrap-record.js:292:20)
    at HTMLDocument._handleKeyEvent (https://easycaped-1.firebaseapp.com/js/external/my-mousetrap.js:775:18)

Error source:
* error

Context:
* Version: 0.68.034
* Started: 2019-08-21T19:00
* Now:     2019-08-21T19:00
* Elapsed: 33.828 sec
* Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.81 Safari/537.36
* Online: true
* Symbol(local)
* Captions
* Logged in

**Comment by lborgman** [comment]
Thanks @dtmpsc , I think this is fixed now (0.70.219).
