### ISSUE TITLE
Uncaught (in promise) ReferenceError: promiseFirstAuthStateChangedDone is not defined

### ISSUE THREAD

**Issue by lborgman** [lborgman/easy-cap-ed#147]
### Steps to Reproduce (if any)
This shows up after a new deploy. Perhaps. 

### Error Popup Message in EasyCapEd (automatically copied)
In URL: 
* https://easycaped-1.firebaseapp.com/pay-stripe.html

ReferenceError: promiseFirstAuthStateChangedDone is not defined
    at getClientSecret (https://easycaped-1.firebaseapp.com/js/stripe/our-stripe.js:24:9)
    at Object.ourPublic.createStripePayButton (https://easycaped-1.firebaseapp.com/js/stripe/our-stripe.js:47:15)
    at https://easycaped-1.firebaseapp.com/js/stripe/our-stripe.js:166:15

Error source:
* unhandledrejection

Context:
* Version: 0.68.080
* Started: 2019-10-11T11:26
* Now:     2019-10-11T11:26
* Elapsed: 10.039 sec
* Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
* Online: true

**Comment by lborgman** [comment]
This seems to be gone. Not sure why.
