### ISSUE TITLE
Error opening the payment page

### ISSUE THREAD

**Issue by lborgman** [lborgman/easy-cap-ed#150]
### Expected Behavior
No error

### Actual Behavior
See below

### Steps to Reproduce
Just open the payment page.

### Error Popup Message in EasyCapEd

In URL: 
* https://easycaped-1.firebaseapp.com/pay-stripe.html

** Unexpected response from fetchJson(url) **
fetch url=(/stripeintent?live=true&payfor=prepay-services&currency=eur&amountstripe=200)

Response status: 500 ()
https://easycaped-1.firebaseapp.com/stripeintent?live=true&payfor=prepay-services&currency=eur&amountstripe=200

Error tracing on browser side:
{
  "browserStack": [
    "Error",
    "    at fetchJson (error.js:615:19)",
    "    at fetchPostJson (error.js:609:18)",
    "    at fetchParamsJson (error.js:587:24)",
    "    at async getClientSecret (our-stripe.js:30:32)",
    "    at async Object.createStripePayButton (our-stripe.js:64:9)"
  ],
  "phase": "response",
  "status": 500,
  "ok": false
}

Response json from server:
{
  "trace": {
    "localVer": "0.0.1",
    "q": {
      "amountstripe": "200",
      "currency": "eur",
      "live": "true",
      "payfor": "prepay-services"
    },
    "where": "b k=idtoken, v=...",
    "b": {
      "idtoken": "..."
    }
  },
  "error": [
    "{ Error: An error occurred with our connection to Stripe.",
    "    (StripeResource.js:212:9",
    "    (StripeResource.js:467:67)",
    "    at ClientRequest.emit (events.js:189:13)",
    "    at ClientRequest.EventEmitter.emit (domain.js:441:20)",
    "    at TLSSocket.socketErrorListener (_http_client.js:392:9)",
    "    at TLSSocket.emit (events.js:189:13)",
    "    at TLSSocket.EventEmitter.emit (domain.js:441:20)",
    "    (destroy.js:82:8)",
    "    (destroy.js:50:3)",
    "    (next_tick.js:63:19)",
    "  raw:",
    "   { message: \u001b[32m'An error occurred with our connection to Stripe.'\u001b[39m,",
    "     detail:",
    "      { Error: getaddrinfo EAI_AGAIN api.stripe.com api.stripe.com:443",
    "          at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)",
    "        errno: \u001b[32m'EAI_AGAIN'\u001b[39m,",
    "        code: \u001b[32m'EAI_AGAIN'\u001b[39m,",
    "        syscall: \u001b[32m'getaddrinfo'\u001b[39m,",
    "        hostname: \u001b[32m'api.stripe.com'\u001b[39m,",
    "        host: \u001b[32m'api.stripe.com'\u001b[39m,",
    "        port: \u001b[32m'443'\u001b[39m } },",
    "  rawType: \u001b[90mundefined\u001b[39m,",
    "  code: \u001b[90mundefined\u001b[39m,",
    "  param: \u001b[90mundefined\u001b[39m,",
    "  detail:",
    "   { Error: getaddrinfo EAI_AGAIN api.stripe.com api.stripe.com:443",
    "       at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)",
    "     errno: \u001b[32m'EAI_AGAIN'\u001b[39m,",
    "     code: \u001b[32m'EAI_AGAIN'\u001b[39m,",
    "     syscall: \u001b[32m'getaddrinfo'\u001b[39m,",
    "     hostname: \u001b[32m'api.stripe.com'\u001b[39m,",
    "     host: \u001b[32m'api.stripe.com'\u001b[39m,",
    "     port: \u001b[32m'443'\u001b[39m },",
    "  headers: \u001b[90mundefined\u001b[39m,",
    "  requestId: \u001b[90mundefined\u001b[39m,",
    "  statusCode: \u001b[90mundefined\u001b[39m,",
    "  charge: \u001b[90mundefined\u001b[39m,",
    "  decline_code: \u001b[90mundefined\u001b[39m,",
    "  payment_intent: \u001b[90mundefined\u001b[39m,",
    "  payment_method: \u001b[90mundefined\u001b[39m,",
    "  setup_intent: \u001b[90mundefined\u001b[39m,",
    "  source: \u001b[90mundefined\u001b[39m,",
    "  type: \u001b[32m'StripeConnectionError'\u001b[39m }"
  ]
}
-------------------------------------

Error source:
* Server Error

Context:
* Version: 0.68.339
* Started: 2019-11-09T20:48
* Now:     2019-11-09T20:48
* Elapsed: 2.663 sec
* Browser: Mozilla/5.0 (Linux; Android 9; motorola one vision) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.96 Mobile Safari/537.36
* Online: true
* Logged in

**Comment by lborgman** [comment]
Fixed in 0.70.198
