### ISSUE TITLE
Error when user not signed in on payment page

### ISSUE THREAD

**Issue by lborgman** [lborgman/easy-cap-ed#151]
### Expected Behavior (if any)
 no error
### Actual Behavior (if any)
Got an error
### Steps to Reproduce (if any)
Just visit the page when not signed in.
### Error Popup Message in EasyCapEd (automatically copied)
In URL: 
* https://easycaped-1.firebaseapp.com/pay-stripe.html

Error: getClientSecret, err TypeError: Cannot read property 'getIdToken' of null
    at getClientSecret (https://easycaped-1.firebaseapp.com/js/stripe/our-stripe.js:35:19)
    at async Object.createStripePayButton (https://easycaped-1.firebaseapp.com/js/stripe/our-stripe.js:64:9)

Error source:
* unhandledrejection

Context:
* Version: > 0.68.106
* Started: 2019-11-11T11:07
* Now:     2019-11-11T11:07
* Elapsed: 0.436 sec
* Browser: Mozilla/5.0 (Linux; Android 9; motorola one vision) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.96 Mobile Safari/537.36
* Online: true
* Not logged in

**Comment by lborgman** [comment]
Fixed in 0.70.198
