### ISSUE TITLE
Error when trying to add line break on first word

### ISSUE THREAD

**Issue by lborgman** [lborgman/easy-cap-ed#159]
### Steps to Reproduce (if any)
Tested the new hyphen + newline

### Error Popup Message in EasyCapEd (automatically copied)
In URL: 
* https://easycaped-1.firebaseapp.com/caped-editor.html?loadFrom=local&key=audio-easycaped-1.firebaseapp.com/tests/UTlmzCIyl80.mp3

Error: newParentP.tagName !== P, SECTION
    at HTMLDivElement.clickFunction (https://easycaped-1.firebaseapp.com/js/caped-editor.js:1612:51)
    at HTMLLIElement.&lt;anonymous> (https://easycaped-1.firebaseapp.com/js/caped-editor.js:757:30)

Error source:
* unhandledrejection

Context:
* Version: 0.71.003
* Started: 2020-07-20T14:49
* Now:     2020-07-20T14:49
* Elapsed: 18.89 sec
* Browser: Mozilla/5.0 (Linux; Android 10; motorola one vision) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Mobile Safari/537.36
* Online: true
* Symbol(local)
* Captions
* Logged in

**Comment by lborgman** [comment]
Fixed in 0.71.005
