### ISSUE TITLE
Unknown attr data-last-saved

### ISSUE THREAD

**Issue by lborgman** [lborgman/easy-cap-ed#160]
### Steps to Reproduce (if any)
Use "Toggle name/alias" in the 3-dots menu.

### Error Popup Message in EasyCapEd (automatically copied)
In URL: 
* https://easycaped-1.firebaseapp.com/caped-editor.html?loadFrom=local&key=audio-easycaped-1.firebaseapp.com/tests/UTlmzCIyl80.mp3

Error: Unknown attr data-last-saved: &lt;p data-t="34200" data-d="39900" class="wordp speaker-name" id="abst00034200P" data-speaker="The Test" data-speaker-alias="T" data-last-saved="&lt;p data-t=&quot;34200&quot; data-d=&quot;39900&quot; class=&quot;wordp speaker-name&quot; id=&quot;abst00034200P&quot; data-speaker=&quot;The Test&quot; data-speaker-alias=&quot;T&quot;>&lt;/p>">&lt;/p>
    at https://easycaped-1.firebaseapp.com/js/sync.js:84:45
    at Array.forEach (&lt;anonymous>)
    at cleanP (https://easycaped-1.firebaseapp.com/js/sync.js:83:17)
    at mkCleanCopyForDatabase (https://easycaped-1.firebaseapp.com/js/sync.js:111:37)
    at requestUpdateEltToDoc (https://easycaped-1.firebaseapp.com/js/caped-editor.js:3047:22)
    at HTMLLIElement.&lt;anonymous> (https://easycaped-1.firebaseapp.com/js/msj/menu3dots.js:143:13)

Error source:
* error

Context:
* Version: 0.71.039
* Started: 2020-07-24T13:17
* Now:     2020-07-24T13:19
* Elapsed: 109.531 sec
* Browser: Mozilla/5.0 (Linux; Android 10; motorola one vision) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Mobile Safari/537.36
* Online: true
* Symbol(local)
* Captions
* Logged in

**Comment by lborgman** [comment]
Fixed in 0.71.040
