### ISSUE TITLE
Error on attempt to move work to "Your cloud"

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#50]
In URL: 
* https://easycaped-1.firebaseapp.com/caped-editor.html?addedNew=YouTube&loadFrom=local&key=YT-wGSB8P1wl1g

Error: elt id not found
    at uploadElt (https://easycaped-1.firebaseapp.com/js/sync.js:318:29)
    at uploadEltFromCopy (https://easycaped-1.firebaseapp.com/js/sync.js:721:38)
    at walkTheElementDOM (https://easycaped-1.firebaseapp.com/js/sync.js:829:5)
    at walkTheElementDOM (https://easycaped-1.firebaseapp.com/js/sync.js:832:9)
    at walkTheElementDOM (https://easycaped-1.firebaseapp.com/js/sync.js:832:9)
    at https://easycaped-1.firebaseapp.com/js/sync.js:751:13
    at <anonymous>

Error source:
* unhandledrejection

Context:
* Version: 0.64.01
* Started: 2018-01-04T10:44
* Now:     2018-01-04T11:42
* Elapsed: 3483.843 sec
* Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
* Symbol(local)
* Logged in

**Comment by lborgman** [comment]
Is this perhaps a duplicate of the error trying to upload to shared cloud? (They should work identically.)

**Comment by lborgman** [comment]
I think this bug is fixed. Setting new label, "maybe bug".
