### ISSUE TITLE
Shared cloud error

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#51]
This error was produced by clicking on the shared cloud button in the dialog that contains the progress bar for upload to the personal cloud. The upload was not complete when I clicked this button.

0.64.01

In URL: 
* https://easycaped-1.firebaseapp.com/caped-editor.html?addedNew=YouTube&loadFrom=local&key=YT-wGSB8P1wl1g

Error: elt id not found
    at uploadElt (https://easycaped-1.firebaseapp.com/js/sync.js:318:29)
    at uploadEltFromCopy (https://easycaped-1.firebaseapp.com/js/sync.js:721:38)
    at walkTheElementDOM (https://easycaped-1.firebaseapp.com/js/sync.js:829:5)
    at walkTheElementDOM (https://easycaped-1.firebaseapp.com/js/sync.js:832:9)
    at walkTheElementDOM (https://easycaped-1.firebaseapp.com/js/sync.js:832:9)
    at https://easycaped-1.firebaseapp.com/js/sync.js:751:13
    at <anonymous>

Error source:
* unhandledrejection

Context:
* Version: 0.64.01
* Started: 2018-01-04T10:44
* Now:     2018-01-04T11:44
* Elapsed: 3584.609 sec
* Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
* Symbol(local)
* Logged in

**Comment by lborgman** [comment]
Thanks @MikeRidgway . It is probably related to the error that upload is not made as a transaction now. (I do not know if it is possible yet, but I think so. I will have to try to do it.)

**Comment by lborgman** [comment]
I believe this is fixed.
