### ISSUE TITLE
Trying to upload to "shared cloud"

### ISSUE THREAD

**Issue by mlockrey** [lborgman/easy-cap-ed#85]
Got this error on Mac OS X and Chrome browser

In URL: 
* https://easycaped-1.firebaseapp.com/caped-editor.html?addedNew=YouTube&loadFrom=local&key=YT-vbiiik_T3Bo

Error: elt id not found
    at uploadElt (https://easycaped-1.firebaseapp.com/js/sync.js:318:29)
    at uploadEltFromCopy (https://easycaped-1.firebaseapp.com/js/sync.js:721:38)
    at walkTheElementDOM (https://easycaped-1.firebaseapp.com/js/sync.js:829:5)
    at walkTheElementDOM (https://easycaped-1.firebaseapp.com/js/sync.js:832:9)
    at walkTheElementDOM (https://easycaped-1.firebaseapp.com/js/sync.js:832:9)
    at https://easycaped-1.firebaseapp.com/js/sync.js:751:13

Error source:
* unhandledrejection

Context:
* Version: 0.64.09
* Started: 2018-01-06T10:07
* Now:     2018-01-06T10:10
* Elapsed: 143.47 sec
* Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3311.3 Safari/537.36
* Symbol(local)
* Logged in

**Comment by mlockrey** [comment]
Then I tried the user cloud option (see screenshot):

In URL: 
* https://easycaped-1.firebaseapp.com/caped-editor.html?addedNew=YouTube&loadFrom=local&key=YT-vbiiik_T3Bo

Error: elt id not found
    at uploadElt (https://easycaped-1.firebaseapp.com/js/sync.js:318:29)
    at uploadEltFromCopy (https://easycaped-1.firebaseapp.com/js/sync.js:721:38)
    at walkTheElementDOM (https://easycaped-1.firebaseapp.com/js/sync.js:829:5)
    at walkTheElementDOM (https://easycaped-1.firebaseapp.com/js/sync.js:832:9)
    at walkTheElementDOM (https://easycaped-1.firebaseapp.com/js/sync.js:832:9)
    at https://easycaped-1.firebaseapp.com/js/sync.js:751:13

Error source:
* unhandledrejection

Context:
* Version: 0.64.09
* Started: 2018-01-06T10:07
* Now:     2018-01-06T10:12
* Elapsed: 277.664 sec
* Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3311.3 Safari/537.36
* Symbol(local)
* Logged in

![screen shot 2018-01-06 at 9 12 36 pm](https://user-images.githubusercontent.com/17226874/34638758-78687f38-f326-11e7-88cc-ea0619d56460.png)

**Comment by lborgman** [comment]
@mlockrey Thanks, did you click anything? Or did you just wait?

The image should say "Ready", but it does not do that. (I need to block the possibility to do anything, but that will have to wait until I implement transactions for upload.)

**Comment by lborgman** [comment]
Hi @mlockrey , could you please try this again?
