### ISSUE TITLE
Error: elt id not found

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#96]
Occurred on Ctrl+Enter.

In URL: 
* https://easycaped-1.firebaseapp.com/caped-editor.html?addedNew=YouTube&loadFrom=local&key=YT-gCH_s7BB3fs

Error: elt id not found
    at mkRec (https://easycaped-1.firebaseapp.com/js/sync.js:56:25)
    at promIdbPutElement (https://easycaped-1.firebaseapp.com/js/sync.js:92:15)
    at updateEltToDoc (https://easycaped-1.firebaseapp.com/js/caped-editor.js:2695:9)
    at setTimeout (https://easycaped-1.firebaseapp.com/js/caped-editor.js:1842:20)

Error source:
* error

Context:
* Version: 0.64.21
* Started: 2018-01-07T22:34
* Now:     2018-01-07T22:39
* Elapsed: 300.658 sec
* Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
* Symbol(local)
* Logged in

**Comment by lborgman** [comment]
@MikeRidgway  Thanks. Adding some more checks to try to understand what is happening. Please report the new error when it happens again. (0.64.23)

**Comment by lborgman** [comment]
Closing for now since we do not see it now.
